### PR TITLE
Automatically call required scripts on install

### PR DESCRIPTION
**Pull request by vkhramtsov**
I think that it will be more convinient if composer execute all required commands automatically

### CODE REVIEW

**Comment by vkhramtsov** [comment]
@muxx , any news about this pr?

**Comment by muxx** [comment]
* Please add information about migration execution on step 3 in "Installation".
* Please update the information in section "Update between 1.x versions".

**Comment by vkhramtsov** [comment]
Updated

**Comment by vkhramtsov** [comment]
@muxx, any news about this PR?

**Comment by FractalizeR** [comment]
Is this project alive? :)

**Comment by muxx** [comment]
Yes :)

**Pull request closed without merging**
