### PR TITLE
Quantile inconsistency fix.

### PR DESCRIPTION
**Pull request by AlexeyKupershtokh**
See #92 for details.

### CODE REVIEW

**Comment by AlexeyKupershtokh** [comment]
Ping @muxx

**Comment by muxx** [comment]
Pull request is ok but can you aggregate all changes in one commit?

**Comment by lisachenko** [comment]
@muxx you can just select merge with squash for this PR ) this feature was recently added.

**Comment by muxx** [comment]
@lisachenko thanks! 👍

**Comment by lisachenko** [comment]
@muxx welcome!

**Pull request merged**
